config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

 
    resources :users
    resources :matches do
      resources :teams, :only => [:new, :create, :edit, :update]
    end
    resources :heroes
    resources :teams, :only => [:index, :show]
    resources :votes, :only => [:new, :create]

  get "/auth/:provider/callback" => "sessions#create"
  delete '/logout' => 'sessions#destroy'
  get "/sessions/login" => 'sessions#index', as: "login"

end

app/models/match.rb
class Match < ActiveRecord::Base
  has_one :player_one, class_name: "User"
  has_one :player_two, class_name: "User"
  has_one :player_three, class_name: "User"
  has_one :player_four, class_name: "User"
  has_many :teams
  
  def votes

    votes = {}

    teams.each do |team|
      id = team.id
      votes[id] = team.votes.count
    end

    return votes
  end

  def self.check_team_membership(id)
    if Team.where(match_id: id).count >= 4
      return false
    else 
      return id
    end
  end

end

# consider extracting to individual team calculations, 
# and having match assemble them as a single object.

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @user = User.find_by(id: session[:user_id])
    @matches = Match.limit(12).order('id desc')

    render :index
  end

  def new
    @user = User.find_by(id: session[:user_id])
    @match = Match.new
    render :create_match
  end

  def create
    @user = User.find_by(id: session[:user_id])
    @match = Match.create(match_create_params[:match])
    @match_id = @match.id
    redirect_to match_path(@match_id)
  end

  def edit
    @user = User.find_by(id: session[:user_id])
    @match = Match.find(params[:id])
    if params[:q]
      @heroes = Hero.find_all(params[:q])
    end
    render :edit
  end

  def show
    @user = User.find_by(id: session[:user_id])
    @match = Match.find(params[:id])
    @teams = @match.teams
    @single_vote = Vote.new
    @votes = @match.votes

    raise
    render :match_page
  end

  def update
  end

  def destroy
  end

  private

  def match_create_params
    params.permit(match: [:name, :stakes, :phase])
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_match_display.html.erb
<div class="mdl-cell mdl-cell--4-col">
  <div class="demo-card-wide mdl-card mdl-shadow--2dp">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text"><%= link_to match.name, match_path(match.id) %></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <strong>Stakes:</strong> <%= match.stakes %><br>
      <% match.teams.each do |team| %>
        <em>Team:</em> <%=link_to team.name, team_path(team.id) %><br>
      <%end%>
    </div>
  </div>
</div>

app/views/matches/_match_form.html.erb
<section>
  <%= form_for @match do |f| %>
    <%= f.label "Match Title" %>
    <%= f.text_field :name %><br><br>
    <%= f.label "Match Stakes" %>
    <%= f.text_field :stakes %><br><br>
    <%= f.hidden_field :phase, value: 1 %>
    <%= f.submit "Create" %>
  <% end %>
</section>

app/views/matches/create_match.html.erb
<section>
  <%= render partial: "match_form", match: @match %>
</section>

app/views/matches/match_page.html.erb
<h2 class="left-pad"><%= @match.name %></h2>
<h4 class="left-pad"><strong>Stakes:</strong> <%= @match.stakes %></h4>


<div class="mdl-grid">
  <section class="mdl-cell mdl-cell--8-col">
  <% if @match.teams.count <= 3 %>
    <%= link_to "Add a team to this match!", new_match_team_path(@match.id), :class => "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
  <%end%>
  </section>

  <section class="mdl-cell mdl-cell--4-col">
  <% if Vote.find_by(user_id: @user.id).nil? && @match.teams.count > 0 %>
    <%= form_for @single_vote, url: votes_path do |f| %>
      <%= hidden_field_tag :user_id, @user.id %>
      <% @teams.each do |team| %>
        <%= radio_button_tag(:team_id, team["id"]) %>
        <%= label_tag(:team_id, team["name"]) %><br>
      <%end%>
      <%= f.submit "Vote!", data: {confirm: 'You have voted on this match. Thank you!'}, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
    <%end%>
    <%else%>
    <p class="mdl-button  mdl-button--raised mdl-button--accent">You already voted on this match!</p>
  <%end%>
  </section>
</div>

<section>
<% @teams.each do |team| %>
  <%= render partial: "/teams/team_block_view", locals: {team: team, match_votes: team.match.votes} %>
<%end%>
</section>