config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

 
    resources :users
    resources :matches do
      resources :teams, :only => [:new, :create, :edit, :update]
    end
    resources :heroes
    resources :teams, :only => [:index, :show]
    resources :votes, :only => [:new, :create]

  get "/auth/:provider/callback" => "sessions#create"
  delete '/logout' => 'sessions#destroy'
  get "/sessions/login" => 'sessions#index', as: "login"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperheroDraft</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <% if flash[:alert].present? -%>
      <div><p><%= flash[:alert] %></p></div>
    <% end -%>
    <%= image_tag("logos/Spotify_Icon_RGB_Green.png", :class => "img-rounded", :width => "50") unless @user %>
    <%= link_to "Login With Spotify", "/auth/spotify" unless @user %>
    
    <% if @user %>
      <% if !@user.image.nil? %>
        <%= link_to image_tag("#{@user.image}", :class => "img-rounded", :width => "100"), "https://open.spotify.com/user/#{@user.uid}" %>
      <% else %>
        <%= link_to image_tag("logos/takeout-tunes-logo.png", :class => "img-rounded", :width => "100"), "https://open.spotify.com/user/#{@user.uid}" %>
      <% end %>

      <%=link_to "#{@user.name}'s", "https://open.spotify.com/user/#{@user.uid}" %> Superhero Draft<br>
      
      <%=link_to "Start a Match", new_match_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"%>

      <%=link_to "See matches", matches_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>

      <%=link_to "See your teams", teams_path, :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>

      <%= link_to "Logout", logout_path, method: "delete", :class => "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>

    <%end %>
  </header>
<br><br>
<%= yield %>
<br><br>
<footer>This app strictly for fun and bar bets. <br>
  All comic book data provided by <%= link_to "Comic Vine", "http://comicvine.gamespot.com/" %>.<br>
   Generic Hero Icon courtesy <%= link_to "Juan Pablo Bravo/Noun Project", "https://thenounproject.com/bravo/" %>.<br> Comic Book Cover icon courtesy <%= link_to "Carlo Cariño/The Noun Project", "https://thenounproject.com/carlocarino/" %>.<br> User icon courtesy <%= link_to "Luis Rodrigues/The Noun Project", "https://thenounproject.com/lmf.rodrigues/" %>.</footer>

</body>
</html>